### ISSUE TITLE
首页进入404错误

### ISSUE THREAD

**Issue by l0rraine** [JingFang-i/laravel-vue-admin#1]
完全按照readme中一步一步走的，最后运行起来之后，直接提示404。
浏览器中F12查看过接口，user和config都返回正常，应该是vue路径配置有问题？
直接使用`php artisan serve`运行的laravel，所以后台端口是8000.相关配置如下：

.env
```
VUE_APP_BASE_API=/admin
VUE_APP_ASSETS_URL=http://localhost:8000/
```

vue.config.js
```
 proxy: {
      '/admin': {
        target: 'http://localhost:8000/admin', // 本地服务器
        ws: false,
        changeOrigin: true,
        pathRewrite: {
          '^/admin': '/'
        }
      }
    }
```

另：`php artisan vendor:publish`里面没有tag为public的选项，是不是readme需要更新下了

**Comment by l0rraine** [comment]
jwt 过期后，不会自动跳转到登录页面，而是显示3条错误信息，就卡住不动了，404都没的看

**Comment by l0rraine** [comment]
建议做一个启动项目，只需要下载者运行`composer install` 和`npm install`就可以运行的那种

**Comment by JingFang-i** [comment]
> jwt 过期后，不会自动跳转到登录页面，而是显示3条错误信息，就卡住不动了，404都没的看

关闭debug模式就可以了，.env文件
```dotenv
APP_DEBUG=false
```

**Comment by JingFang-i** [comment]
> 建议做一个启动项目，只需要下载者运行`composer install` 和`npm install`就可以运行的那种

后面会考虑，目前需要配置的是有点多，不同环境下确实存在问题．安装dev-master确保是最新的．

> 完全按照readme中一步一步走的，最后运行起来之后，直接提示404。
> 浏览器中F12查看过接口，user和config都返回正常，应该是vue路径配置有问题？
> 直接使用`php artisan serve`运行的laravel，所以后台端口是8000.相关配置如下：
> 
> .env
> 
> ```
> VUE_APP_BASE_API=/admin
> VUE_APP_ASSETS_URL=http://localhost:8000/
> ```
> 
> vue.config.js
> 
> ```
>  proxy: {
>       '/admin': {
>         target: 'http://localhost:8000/admin', // 本地服务器
>         ws: false,
>         changeOrigin: true,
>         pathRewrite: {
>           '^/admin': '/'
>         }
>       }
>     }
> ```
> 
> 另：`php artisan vendor:publish`里面没有tag为public的选项，是不是readme需要更新下了

建议安装dev-master版本或者最新的v0.3版本，你提到的这些问题，我会自己测试下，感谢．
