### ISSUE TITLE
您好,请问下我按照您的前端步骤走到最后,提示"View [index] not found."

### ISSUE THREAD

**Issue by gengsende** [JingFang-i/laravel-vue-admin#2]
![image](https://user-images.githubusercontent.com/23625903/93289510-16456300-f811-11ea-8e4d-f9fa31c6e603.png)

**Comment by gengsende** [comment]
我是用
`composer create-project laravel/laravel laravel-vue-admin --prefer-dist "7.*.*"`
创建的项目,然后用您的文档一步步来的,前端package.json文件是好像是laravel自带的
![image](https://user-images.githubusercontent.com/23625903/93290759-04b18a80-f814-11ea-83d4-55398d86ec2c.png)
没有  `npm run build:prod`这个构建命令,我就用  `npm run production`

**Comment by JingFang-i** [comment]
你需要在routes/web.php 中配置下路由
```php
Route::get('/', function () {
    return view('index');
});
```

**Comment by JingFang-i** [comment]
> 我是用
> `composer create-project laravel/laravel laravel-vue-admin --prefer-dist "7.*.*"`
> 创建的项目,然后用您的文档一步步来的,前端package.json文件是好像是laravel自带的
> ![image](https://user-images.githubusercontent.com/23625903/93290759-04b18a80-f814-11ea-83d4-55398d86ec2c.png)
> 没有 `npm run build:prod`这个构建命令,我就用 `npm run production`

建议重新执行命令发布资源, 需要加上--force强制覆盖
```shell script
php artisan vendor:publish --force
```
