### ISSUE TITLE
登录后台显示404，/auth 返回menu和permission为空

### ISSUE THREAD

**Issue by nihao10086** [JingFang-i/laravel-vue-admin#4]
按照流程一步步安装后，数据库可以访问，
设置后台账号密码为admin/123456 

1  登录后，依次访问/user返回正常，访问/auth返回menu和permission为空，然后跳转到404.

查看数据表 没有给admin设置权限，roles，model_has_roles,model_has_permissions都是空，

admin.sql没有给admin设置权限的sql

现在不确定是不是这个原因，
2 修改部分代码进入后台，
  角色管理无法分配权限

**Comment by JingFang-i** [comment]
以上问题已解决，请安装最新版本。
